BOOTMAGIC_ENABLE = no       # Enable Bootmagic Lite for runtime debug toggle
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = yes        # Console for debug
COMMAND_ENABLE = yes        # Commands for debug and configuration
NKRO_ENABLE = yes
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
AUDIO_ENABLE = yes          # Audio output
RGBLIGHT_ENABLE = no        # Enable WS2812 RGB underlight.
TAP_DANCE_ENABLE = yes
CAPS_WORD_ENABLE = yes
